### ISSUE TITLE
using urlparse instead of regular expression

### ISSUE THREAD

**Issue by xrogaan** [lpenz/ftpsync#1]
You should use urlparse instead of the re module.
More information about urlparse : http://docs.python.org/library/urlparse.html

If you want, i can take that one.

**Comment by lpenz** [comment]
Sure, that would be great!

**Comment by xrogaan** [comment]
If that's ok, the file .ftp_upstream should contain only the url, without the keyword "upstream".

**Comment by lpenz** [comment]
I see no problem with that. In fact, it a bit redundant with the name of the file.
The initial idea was to have other options in the file, but I can't think of any. Anyway, if we need more options, we can use a file called .ftpsync instead, and look for it before .ftp_upstream.

**Comment by xrogaan** [comment]
They will be an option, later, to specify manually the keychain to get from gnome-keyring.

Actually, the user need to unlock the keychain before lauching ftpsync. I'm working to fix that.

Note : this issue is fixed, i just need to push the changes.

**Comment by xrogaan** [comment]
Fixed in db1c479c366464eb0fe5817740d2fd166f1e4077
